# .readthedocs.yaml
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  version: "3.11"  # Ensure this is in the correct place without dot notation
  install:
    - method: pip
      path: .

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
