# Required version
version: 2

# OS and Python setup
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install dependencies and package
python:
  version: 3.11
  install:
    - method: pip
      path: .

# Use Sphinx to build docs
sphinx:
  configuration: docs/source/conf.py

# Enable additional Sphinx extensions
python:    
  install:
    - requirements: rtd_requirements.txt